# Generated by Django 5.0.3 on 2024-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology'), ('trivia', 'Trivia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='region',
            field=models.CharField(choices=[('uk', 'UK'), ('eu', 'EU'), ('w', 'World')], max_length=2),
        ),
    ]
