# Generated by Django 5.0.3 on 2024-04-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_aggregator', '0002_alter_story_author_alter_story_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='unique_key',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
